FROM nginx:alpine

# Копируем файлы визуализатора
COPY visualizer.html /usr/share/nginx/html/index.html
COPY visualizer.html /usr/share/nginx/html/visualizer.html
COPY visualizer.css /usr/share/nginx/html/visualizer.css
COPY visualizer.js /usr/share/nginx/html/visualizer.js
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Создаем директорию для данных
RUN mkdir -p /usr/share/nginx/html/data

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
